# Usage:
# databend-query -c databend_query_config_spec.toml

# Query
[query]
max_active_sessions = 256

# For flight rpc.
flight_api_address = "0.0.0.0:9091"

# Databend Query http address.
# For admin RESET API.
http_api_address = "0.0.0.0:8081"

# Databend Query metrics RESET API.
metric_api_address = "0.0.0.0:7071"

# Databend Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3307

# Databend Query ClickHouse Handler.
clickhouse_handler_host = "0.0.0.0"
clickhouse_handler_port = 9001

# Databend Query HTTP Handler.
http_handler_host = "0.0.0.0"
http_handler_port = 8001

namespace = "test_cluster"

# Log
[log]
log_level = "DEBUG"
log_dir = "./_logs"

# Meta service.
[meta]
meta_address = "0.0.0.0:9191"
meta_username = "root"
meta_password = "root"
meta_client_timeout_in_second = 60

# Storage config.
[storage]
# disk|s3
storage_type = "disk"

# DISK storage.
[storage.disk]
data_path = "stateless_test_data"

# S3 storage.
[storage.s3]
