[package]
name = "common-planners"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
# Workspace dependencies
common-datavalues = {path = "../datavalues"}
common-functions = {path = "../functions"}
common-exception = {path = "../exception"}
common-datablocks = {path = "../datablocks"}
common-infallible = {path = "../infallible"}
common-meta-types = {path= "../meta/types" }
common-streams = {path= "../streams" }

# Github dependencies

# Crates.io dependencies
serde = { version = "1.0", features = ["derive"] }
futures = "0.3"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "1.0"
